### ISSUE TITLE
[bug] "Take compared file"

### ISSUE THREAD

**Issue by iSentrie** [moshfeu/vscode-compare-folders#104]
![image](https://user-images.githubusercontent.com/29688478/186848331-8e48c31a-0168-41ac-8e45-775353c96c7b.png)

So earlier it have worked most of the time, but now for couple of weeks this function doesn't work at all, simply nothing happens or changes when clicked on "Take compared file".

Details: 

**VS CODE**
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000 (Win 11)

Do you need any other details?

**Comment by moshfeu** [comment]
Thank you!
I couldn't reproduce the issue but I have a different operation system.
- Are you using the latest version of the extension? (0.22.2)
- Is this happening in all files and folders or specific ones?
- Do you see anything in the Output panel under Compare Folders?

<img width="500" alt="Screen Shot 2022-08-26 at 20 16 24" src="https://user-images.githubusercontent.com/3723951/186958012-a662d561-3b53-45ba-89e0-8ffe4b009011.png">

**Comment by iSentrie** [comment]
> Thank you! I couldn't reproduce the issue but I have a different operation system.
> 
> * Are you using the latest version of the extension? (0.22.2)
> * Is this happening in all files and folders or specific ones?
> * Do you see anything in the Output panel under Compare Folders?
> 
> <img alt="Screen Shot 2022-08-26 at 20 16 24" width="500" src="https://user-images.githubusercontent.com/3723951/186958012-a662d561-3b53-45ba-89e0-8ffe4b009011.png">

- Are you using the latest version of the extension? (0.22.2)
yes ![image](https://user-images.githubusercontent.com/29688478/187035240-53e04810-b8f4-4e60-9b78-2f559f0ebf5b.png)
- Is this happening in all files and folders or specific ones?
at first i noticed that it doesn't work if i comparing with network folders, which is in other computer (local network), BUT NOW it doesn't work anywhere I put it...
- Do you see anything in the Output panel under Compare Folders?
**ok so, i tried today all this again and everything is working just fine, idk why or how, this is very weird, but it started to work as intended again, even in networked folders.... 🤔 i hope it wont break again, i think we can close this for now, because i can't really give any details if it works now. 😳

**Comment by moshfeu** [comment]
Thank you for deep and continues check!
I'll check the `.` issue and will add a validation if the extension can't handle folders with `.`
