### ISSUE TITLE
VSCode v1.71.0 in Ubuntu the button "Click to select a folder" stopped working

### ISSUE THREAD

**Issue by RoKov2017** [moshfeu/vscode-compare-folders#105]
After the update to VSCode v 1.71.0 in Linux, the button "Click to select a folder" stopped working and there is no way to add a folder for comparison.
https://imgur.com/9ponMjg

**Comment by moshfeu** [comment]
Can you check my fix please?

[compare-folders-0.22.3.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/9483415/compare-folders-0.22.3.vsix.zip)

**Comment by Zvika88** [comment]
The fix works (downloaded the zipfile from the link above).
Thanks for the quick response Mosh!

**Comment by moshfeu** [comment]
Thank you @Zvika88 for verifing!

**Comment by moshfeu** [comment]
Deployed
