### ISSUE TITLE
[feature request] Ability to use Git blame/change history overlay from Gitlens with Compare Folders view

### ISSUE THREAD

**Issue by ansonl** [moshfeu/vscode-compare-folders#114]
Hi, great extension! It does exactly what I expected it to do. Making this issue as requested.

Sometimes I would compare two files' text with the "select for compare/compare with selected" options and I use the [Gitlens extension](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) to show git blame/history overlay between the two files where it shows the git info next to the appropriate line like below:

![image](https://user-images.githubusercontent.com/546458/211058967-478c3771-d193-42ec-8635-9506ec80a702.png)

The Gitlens extension button to show the git blame/history overlay is shown in the upper right of the editor tab when I compare two files without using Compare Folders but the buttons are not shown when using Compare Folders to compare two files even though the displayed 2 column "diff" interface looks similar. 

I'm not familiar with how vscode extensions work so I assume that this may be a limitation with Gitlens or Vscode. But maybe there is an easy way to use Gitlens git overlays within Compare Folders.

**Comment by moshfeu** [comment]
Thank you! Really appreciate ❤️ 

The extension is using the built-in "diff view" (opened by [`vscode.diff`](https://code.visualstudio.com/api/references/commands#:~:text=%2D%20no%20result-,vscode.diff,-%2D%20Opens%20the%20provided). I believe that it's the same view as "select for compare/compare with selected"'s.

I do see that git blame button for the diff view presented by compareFolders

https://user-images.githubusercontent.com/3723951/211493218-117510c7-a10c-4e0d-9afa-c106011eb458.mov
