### ISSUE TITLE
No hover effect for sidebar icon?

### ISSUE THREAD

**Issue by niccolomineo** [moshfeu/vscode-compare-folders#116]
Hi @moshfeu, I [reached out](https://github.com/microsoft/vscode/issues/174031) to the guys at VSCode asking why some extensions' sidebar icons do not have a proper hover effect like the default ones, and they said it's up to the extension creator to deal with it.

Would you be able to implement it to make the UI more consistent?

This is what I am talking about:

Any default VSCode sidebar icon:

![218056442-31ae9bf2-6245-4102-91e2-a65e480b8f3f](https://user-images.githubusercontent.com/5409469/223436982-f2d31c44-504e-4831-8582-5e7bce52cf8c.png)

Compare Folders's icon:

<img width="341" alt="Screenshot 2023-03-07 alle 14 54 43" src="https://user-images.githubusercontent.com/5409469/223442825-f5c2c44c-4323-403a-a0fd-81b96a6d58dd.png">

**Comment by moshfeu** [comment]
Thank you for your feedback!
I'm very busy these days so it might take me some time to get into it but I will.

**Comment by niccolomineo** [comment]
Hi, apparently there is a way to do it using a woff glyph - I've learnt it's how Gitlens does it. I prepared it for you. Find it attached together with the source and in a bunch of other extensions:

[CompareFolders.zip](https://github.com/moshfeu/vscode-compare-folders/files/11226970/CompareFolders.zip)

Let me know should you need to tweak it further.

**Comment by moshfeu** [comment]
It took me some time to learn how to use the font as icon but I got this.
Thanks for taking the time to find the solution 🙏 ☺️

**Comment by niccolomineo** [comment]
> It took me some time to learn how to use the font as icon but I got this.
> Thanks for taking the time to find the solution 🙏 ☺️

Cool, can't wait to see the hover effect working as it should. 👍
