### ISSUE TITLE
Sidebar icon outline too thin

### ISSUE THREAD

**Issue by niccolomineo** [moshfeu/vscode-compare-folders#117]
Hi @moshfeu, I see the icon has a visibly thinner outline than the default ones.

Would you be able to change it to comply with VSCode's current icon set style guide?

<img width="39" alt="Screenshot 2023-03-07 alle 14 57 45" src="https://user-images.githubusercontent.com/5409469/223443695-cf462691-df6f-40eb-9a34-35c6a5fb413d.png">

**Comment by moshfeu** [comment]
Thanks @niccolomineo. I appreciate that you care so much about UI :) I can relate.

Anyway, I couldn't find vscode guidelines specifically for the line width of the icon but I made it a bit wider. 
What do you think about this version?

[compare-folders-0.22.4.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/11145446/compare-folders-0.22.4.vsix.zip)


Note that my skills of editing SVGs is very limited so I don't have much to do.

**Comment by moshfeu** [comment]
You are right 🤦‍♂️ It only changes the color a bit.
I tried to make the icon wider by setting the svg path`path` `stroke=1px`.
Unfortunately it's not a good solution because vscode uses css mask to show the icon which doesn't consider stroke.

The `path` coords are Jibrish to me so I don't have a clue how to adjust the path to be wider.
If you have ideas or tools, please let me know.

Thanks

**Comment by niccolomineo** [comment]
> You are right 🤦‍♂️ It only changes the color a bit.
> 
> I tried to make the icon wider by setting the svg path`path` `stroke=1px`.
> 
> Unfortunately it's not a good solution because vscode uses css mask to show the icon which doesn't consider stroke.
> 
> 
> 
> The `path` coords are Jibrish to me so I don't have a clue how to adjust the path to be wider.
> 
> If you have ideas or tools, please let me know.
> 
> 
> 
> Thanks

You could try expanding the stroke in Illustrator or a tool like that

**Comment by niccolomineo** [comment]
If you want you can send it over and I can give it a shot.

**Comment by moshfeu** [comment]
It's been a while since I engaged with Illustrator 😅 

> If you want you can send it over and I can give it a shot.

That would be great. Thanks.

You can find the icon here https://github.com/moshfeu/vscode-compare-folders/blob/master/resources/icon.svg

<img width="100" src="https://raw.githubusercontent.com/moshfeu/vscode-compare-folders/master/resources/icon.svg" />

**Comment by niccolomineo** [comment]
> It's been a while since I engaged with Illustrator 😅
> 
> > If you want you can send it over and I can give it a shot.
> 
> That would be great. Thanks.
> 
> You can find the icon here https://github.com/moshfeu/vscode-compare-folders/blob/master/resources/icon.svg
> 
> <img alt="" width="100" src="https://raw.githubusercontent.com/moshfeu/vscode-compare-folders/master/resources/icon.svg">

Here you go. This should be more like what we're aiming at.

![icon](https://user-images.githubusercontent.com/5409469/229801664-81a4ed41-aa88-4df2-92c3-a5075ac2b86a.svg)

**Comment by niccolomineo** [comment]
> Very nice! I should take a lesson from you.
> Please, take the honor to add it by your self so the improvement will be on your name :)
> Can you create a PR for this?

Sure I am going to, thanks.

**Comment by moshfeu** [comment]
Released! Thank you so much.
If you have more ideas or suggestions, please let me know.
My time is very limited right now but maybe we can collaborate again :)

**Comment by niccolomineo** [comment]
The product icon could be made more visible, but you would just need to get an icon off from somewhere.

This is on my dark theme:

![Screenshot 2023-04-06 alle 23 53 05](https://user-images.githubusercontent.com/5409469/230500827-0df1ebf8-c2c1-4f5f-9976-ba750b29f03f.png)

**Comment by moshfeu** [comment]
Thanks, you are right!
What do you think about this kind of icon?

![AppIcon_512x512x32](https://user-images.githubusercontent.com/3723951/231674482-74a75dcd-5782-4491-8d7e-46b80875b071.png)

**Comment by moshfeu** [comment]
Deployed
