### ISSUE TITLE
[Bug] Files appear to be different but they are not

### ISSUE THREAD

**Issue by gpanag93** [moshfeu/vscode-compare-folders#119]
In some cases, there are certain files that appear in the "Differences" tab but when opened and closely inspected they are identical.

**Comment by moshfeu** [comment]
Thanks for reporting!
Can you upload these 2 files? Maybe it's something with white spaces which the IDE configured to ignore or invisible characters..

**Comment by LewisHoneypot** [comment]
I had this issue too, i fixed it by right clicking and choosing "take my file" or "take compared file", seems that either choice is fine as the files are the same.

**Comment by moshfeu** [comment]
> I had this issue too, i fixed it by right clicking and choosing "take my file" or "take compared file", seems that either choice is fine as the files are the same.

Nice idea, thanks 😊
