### ISSUE TITLE
Handling directory comparison mismatch

### ISSUE THREAD

**Issue by gliviu** [moshfeu/vscode-compare-folders#127]
Regarding https://github.com/moshfeu/vscode-compare-folders/issues/126#issuecomment-1666727423.
If we consider this sample folder:
[test126.zip](https://github.com/moshfeu/vscode-compare-folders/files/12324702/test126.zip)

```
├── a1.txt
├── a2.txt
├── b1.txt              [include]
├── .gitignore       -> a*
└── x                       [include]
    ├── a1.txt
    ├── a2.txt
    ├── a3.txt
    ├── a4.txt
    └── b2.txt           [include]
```

According to .gitignore, only the files marked with `[include]` above, should be shown.
If I use vscode-compare-folders, and compare this folder against an empty folder, I get this result:
![image](https://github.com/moshfeu/vscode-compare-folders/assets/8597812/8993db6b-226d-4d88-b2b6-2ebead1f1be9)

It looks like it excludes all files except .gitignore. It should not exclude b1 and b2.

I added [some logs](https://github.com/gliviu/vscode-compare-folders/blob/test_issue_126/src/services/comparer.ts#L136) to investigate. And this is how dir-compare is called and its response.

Options:
```
{
  ...
  "excludeFilter": ".git,a*",
  "includeFilter": "*",
  ...
}
```
And dircompare response:
```
Directories are different
Statistics - equal entries: 0, distinct entries: 0, left only entries: 4, right only entries: 0, differences: 4
b1.txt undefined left
x undefined left
b2.txt undefined left
.gitignore undefined left
```
The response from dircompare looks good. It correctly excludes a*, .git and includes everything else (b1, b2, .gitignore).

I am unsure now where is the problem. Maybe it is related to the way dircompare result is handled by vscode-compare-folders.

**Comment by moshfeu** [comment]
I've added the types to the log

```ts
result.diffSet.forEach(dif => console.log(`${dif.name1} ${dif.name2} ${dif.state} ${dif.type1} ${dif.type2}`))
```

and the result is

```
b1.txt undefined left directory missing
x undefined left directory missing
b2.txt undefined left directory missing
.gitignore undefined left file missing
```

Since the extension is about comparing **files**, it filters out diffs which have type anything but "file", like here

https://github.com/moshfeu/vscode-compare-folders/blob/ecdb0d2b8048763a2bd9b73deed9bd32e83ba41e/src/services/comparer.ts#L134-L135

In the result, the only `file` diff is the _.gitignore_'s
