### ISSUE TITLE
Make the file compare tab title more informative

### ISSUE THREAD

**Issue by jsabotage52** [moshfeu/vscode-compare-folders#13]
While using this tool, I think it would be very helpful to make the diff tab title match what the built in file compare does for VSCode.

Note that the built in compare tab title says "File.txt <-> C:\Right Folder\File.txt"
![Built_in_file_compare](https://user-images.githubusercontent.com/15022570/72355346-443c3b80-36b5-11ea-9806-9a6233b0c778.PNG)

Whereas this extension is less informative and only says "File.txt"
![Compare_Folders](https://user-images.githubusercontent.com/15022570/72355353-47372c00-36b5-11ea-8169-7d836dfc67cb.PNG)

**Comment by moshfeu** [comment]
Thanks you!
Basically, I get your point. Although, the built-in diff view in running out of context.
In the extension the user has the context because they chosen which folder to compare.

Maybe, adding the compared path to the `only in compared folder` section's title?

**Comment by jsabotage52** [comment]
That seems like a reasonable solution. Could put the base path in the `only in my folder` section's title as well.

However if you don't have the extension selected on the left, you'll have to click back to see this. Not really a problem though.

**Comment by moshfeu** [comment]
Actually, I can let the user to choose :)
I'll add an option in the settings, "show minimal title".

**Comment by moshfeu** [comment]
@jsabotage52 I created a new version, can you check it?
1. Download [compare-folders-0.6.0.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/4061294/compare-folders-0.6.0.vsix.zip)
2. Unzip, you should get .vsix file
3. Install it

<img src="https://user-images.githubusercontent.com/3723951/71930889-3e21f880-31a5-11ea-8e07-9be70cf67054.png" />

Thanks!
