### ISSUE TITLE
[feature request] On diff, allow line changes to go both ways

### ISSUE THREAD

**Issue by rosskevin** [moshfeu/vscode-compare-folders#130]
We are finding that from current to compareSet, we sometimes want to take the line change from the compareSet back to current.  As-is, we can only `->` send changes, but it would be nice to `<-` take changes.

**Comment by moshfeu** [comment]
Hi @rosskevin, this is a great idea :) but..
The extension uses the built-in diff view of vscode (using [`vscode.diff`](https://code.visualstudio.com/api/references/commands#:~:text=%2D%20no%20result-,vscode.diff,-%2D%20Opens%20the%20provided) command so unfortunately I don't think it's possible.
You can always swap the sides of the comparison so you could change the other ways

<img width="416" alt="Screenshot 2023-09-09 at 20 25 34" src="https://github.com/moshfeu/vscode-compare-folders/assets/3723951/a4c56aba-c492-4c40-913a-a0b54ab12917">

**Comment by Tobbe** [comment]
Came here to ask for this feature as well. Would be awesome to have 🙂. Swapping sides works, but is kind of slow as it has to recompute everything.

Here's the upstream issue to track: https://github.com/microsoft/vscode/issues/153620

**Comment by moshfeu** [comment]
@Tobbe Would it help if I added an option to open the pair in the opposite direction? So if the normal comparison opened as A file in the left and B file in the right it will be B in the left and A in the right

Why not?
1. The experience is odd
2. Still not possible to copy both ways in the same comparison

**Comment by Tobbe** [comment]
@moshfeu Thanks for getting back to me. 

I'd say probably not worth it 🙂  Just leave it the way it is until a "proper" solution can be implemented

**Comment by moshfeu** [comment]
Thanks @Tobbe 🙏
