### ISSUE TITLE
stopped comparing whitespaces on a row

### ISSUE THREAD

**Issue by nikolay-bakardzhiev** [moshfeu/vscode-compare-folders#132]
Type: <b>Bug</b>

Dears,
In previous versions the compare extension compared whitespaces on an empty row and marked them with different colors. 
The latest version do not mark the whitespaces with different color but mark the whole row as s difference. Is it possible to return the old behavior where just the difference (whitespaces) will be marked with dark red on top the red marking of the whole row? 
The same issue do not persist when there is a string in the same row. In this case the whitespaces are marked correctly. The issue is only when the row containes whitespaces.

Version: 1.83.0 (Universal)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:15.449Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

Extension version: 0.23.0
VS Code version: Code 1.83.0 (Universal) (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:13:15.449Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id ff278e42-6885-4bac-bd7e-429d1e36432d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
vscrp:30673768
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
pythonmhint1:30842940
dsvsc015:30845448

```

</details>

**Comment by moshfeu** [comment]
Thanks for reporting the issue (and sorry for the late reply)

The differences view is vscode's. The extension just uses its api, pass the 2 files path so I'm not sure there is something to do to go back to the previous behaviour. Maybe it's possible to control the behaviour of the diff view via settings. Maybe `editor.renderWhitespace` setting?
