### ISSUE TITLE
Add ability to swap which folder is "left" and "right" with a simple button click

### ISSUE THREAD

**Issue by jsabotage52** [moshfeu/vscode-compare-folders#14]
I use Beyond Compare 4 a good bit, and I like the option it provides to swap left vs. right folders.

See the far right button?
![image](https://user-images.githubusercontent.com/15022570/72356236-ea3c7580-36b6-11ea-8bd9-4a8fbb5511b5.png)

Is it possible to implement something like this in the VSCode extension? I realize since the "left" folder comes from the workspace this might not be possible.

**Comment by moshfeu** [comment]
Thank you!
It can be possible with the right changes in the code ;)
A workaround for now is open the "right" folder in vscode and compare it to the left..

**Comment by moshfeu** [comment]
I pre-released [v0.11.0](https://github.com/moshfeu/vscode-compare-folders/releases/download/v0.11.0/compare-folders-0.11.0.vsix). Please install it and verify the feature is working as expected.
Thanks!
