### ISSUE TITLE
Show Identical Files Switch doesn't work

### ISSUE THREAD

**Issue by DMSTEX-Duane** [moshfeu/vscode-compare-folders#144]
### Navigation
1. File --> Preferences --> Settings
1. "User" Tab
1. Extensions --> Compare Folders --> Show Identical

### Results
1. No matter if set or not, matching (identical?) files are displayed in the "Differences" panel.
1. Clicking "X" on a file in the "Differences" panel does not dismiss the file.  It remains displayed in the panel.

### Notes
- The "Workspace" Tab seems to work the same as the "User" Tab.
- I looked for a duplicate issue or fix description online, but I could not find one.

**Comment by DMSTEX-Duane** [comment]
Found a similar issue: https://github.com/moshfeu/vscode-compare-folders/issues/119

My bad.  **Please close as this is working correctly.**

I added the following settings and I don't get matching (but not identical) files listed anymore.
- Ignore all White Spaces
- Ignore Empty Lines
- Ignore Line Ending

Thank you for maintaining a good quality extension.

**Comment by moshfeu** [comment]
You are mych welcome :)
