### ISSUE TITLE
View as list like source control

### ISSUE THREAD

**Issue by michaelmesser** [moshfeu/vscode-compare-folders#151]
The source control view allows toggling between seeing changes as a list and seeing changes as a tree.
This extension shows the changes as a tree by default. Is it possible to show the changes as a list?

**Comment by moshfeu** [comment]
Thanks for the suggestion and sorry for the late reply 😅 

Would you mind giving it a try and let me know what you think?

[compare-folders-0.25.0.vsix.zip](https://github.com/user-attachments/files/16759457/compare-folders-0.25.0.vsix.zip)
