### ISSUE TITLE
Update tree when editing/merge files

### ISSUE THREAD

**Issue by llgcode** [moshfeu/vscode-compare-folders#16]
It will be great that difference tree updates when edit/merge file, so we can see live it changes.

**Comment by moshfeu** [comment]
Currently, there is the refresh button

![Screen Shot 2020-02-18 at 13 13 07](https://user-images.githubusercontent.com/3723951/74731334-74e13900-5250-11ea-815d-a35dfc233392.png)

Comparing for each save sounds fair to me.
Of course, there will be an option to turn it off so for large projects it will not cause performance issues.

Thanks!

**Comment by llgcode** [comment]
You might update only the file that has changed in the tree without any performance cost

**Comment by moshfeu** [comment]
Indeed, this is a better approach, I was thinking about "time to develop" compare "value". Compare all over again, in most of the cases will be good enough and require less time to develop.
WDYT?

**Comment by llgcode** [comment]
I have big projects and it could be very long to compare again and again.
I don't think it is long to develop cause extension API provides easy way to lookup file changes:
https://code.visualstudio.com/api/references/vscode-api

createFileSystemWatcher(globPattern: GlobPattern, ignoreCreateEvents?: boolean, ignoreChangeEvents?: boolean, ignoreDeleteEvents?: boolean): FileSystemWatcher

**Comment by moshfeu** [comment]
Anyway the extension will need listen to changes. 
With the "compare all" approach, this is the only thing that need to be added.
With the "compare only changed file" there are more things to do.

I agree that the "compare only changed file" is better.

I'm curios, how long it takes to compare your project in the first time or when you hit "refresh"?

**Comment by moshfeu** [comment]
Keep
