### ISSUE TITLE
File Copy Button does not work

### ISSUE THREAD

**Issue by stefanc82** [moshfeu/vscode-compare-folders#162]
Type: <b>Bug</b>

On the "ONLY IN COMPARED FOLDER" section, the copy button does not copy the file.
It only works when using the copy button on a parent folder.

Extension version: 0.25.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13650HX (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (17.18GB free)|
|Process Argv|--crash-reporter-id e5f860dd-5001-45d4-ad2b-9c8cb79d3a64|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31150322
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by moshfeu** [comment]
Hi Stefan,

Thanks for reporting this. I'll look into it as soon as I can

**Comment by moshfeu** [comment]
It's not reproduced on my Mac so I'm trying to get windows..

Can you go to the OUTPUT panel and select Compared Folders from the dropdown. There you can see bunch of logs. Can you see if there are an error there?

Here is how
<img width="1362" alt="Screenshot 2024-10-12 at 23 11 28" src="https://github.com/user-attachments/assets/f02707f6-f7cd-49a2-b35f-976b6e5ca1f6">

**Comment by EmanuelAlejandro1988** [comment]
Hi @moshfeu ! I hope you are well.

I have the same issue: 

Error log: {
  "errno": -4058,
  "code": "ENOENT",
  "syscall": "stat",
  "path": "c:\\BOT\\CLOUDVERSION3\\c:\\text.txt" 

It seems that in Windows it does not take the destination path completely, in the log it shows that it tries to copy directly to the directory in C: and the path is not that, the path is c:\\BOT\\CLOUDVERSION_OLD\.
}

Could you guide me how to solve it?

Thank you so much!

**Comment by moshfeu** [comment]
I think I fixed it.
Can you try this test version?

[compare-folders-0.25.1.vsix.zip](https://github.com/user-attachments/files/17525859/compare-folders-0.25.1.vsix.zip)
