### ISSUE TITLE
copy files not working

### ISSUE THREAD

**Issue by webDaeve** [moshfeu/vscode-compare-folders#164]
For the past couple of weeks, I've been experiencing an issue where attempting to copy files to either the "compared" or "original" folder doesn't trigger any action. Both folders are located on my computer. I've tested this with PHP, JS, CSS, and image files, but nothing happens when trying to copy.
The functionality to choose between compared files when they exist in both folders works fine.
The issue only occurs when the file exists in one folder but not the other.
Please advise on how to resolve this or if any further troubleshooting steps are required.

in the output panel i get this log:

{
  "errno": -4058,
  "code": "ENOENT",
  "syscall": "stat",
  "path": "c:\\xampp56\\htdocs\\vivisalutedario\\c:\\app\\Console\\Commands\\MailInattivitaTelelavoro.php"
}

Thank you

**Comment by moshfeu** [comment]
Thanks for reporting @webDaeve 
I wonder if it's the same as #162 . Can you paste here your [vscode environment information](https://code.visualstudio.com/docs/supporting/FAQ#:~:text=On%20Windows%20and%20Linux%2C%20go,has%20the%20version%20format%20'major.)?

**Comment by webDaeve** [comment]
This one?

Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045



-Dario Vimercati

Web Designer & Developer

P.IVA 11797800965

[https://3lf2h.img.bh.d.sendibt3.com/im/2032375/63127b8f0336a9aa4a776c08daaac464dd55914c3e5722bdea6a578751fd1a36.jpg?e=kTqq8IThH0l-wVd57rpiW5klWCFAcwzpS2uKpaPISPW72tscsvnlc4Vp8kcRvMqSsCwbw8WEAjQ1ta0cVRynODm4loZH40l0yLDlcRWsW5tMmCeN77SZF9NHVjom4ZfvN4c5R1ODyEPLgAJx7kPQQJuzPJq47DQdT2Sy_82TrS6e6zWLqZtUcAcU85A-tXHy7o26NhWjky2A0ej5a3TYAVfUm7gibV-uCtCvMsZB9Q4tMJ09bt6KST8CLgC4aJkPi6vUbOjWtS-23o58VDfsP5Jm3zsrlQrNEKcAMbPY5MDwUJO8BIdi3NOTWBkTGwOBMyN-GTjWirUgF-LWNp4HP43W6gxAME7SpbTAZUbgxstDXH1XIzL9Un-C8MAhqnM3A8WEqeSKD0Gs]

________________________________

**Comment by HRading** [comment]
I experience the same issue, not being able to copy. It used to work in the old version where I had to right-click and select copy..
in the new one with icons, it is not working.

my env details:
Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by moshfeu** [comment]
I'm working on getting windows and I'll check that

It's probably somewhere here
https://github.com/moshfeu/vscode-compare-folders/blob/d9fd84a636e798c14d90356abff72913fe45a30b/src/providers/foldersCompareProvider.ts#L271-L274

so if anyone get a chance to check this too, it would be great

In the meantime, you can downgrade to the previous version, I think it's started in the latest version

**Comment by moshfeu** [comment]
Same as #162

**Comment by moshfeu** [comment]
I think I fixed it.
Can you try this test version?

[compare-folders-0.25.1.vsix.zip](https://github.com/user-attachments/files/17525859/compare-folders-0.25.1.vsix.zip)

**Comment by webDaeve** [comment]
you did it! thanks a lot

**Comment by moshfeu** [comment]
Thank you :)
New version just published

**Comment by noumanhabib** [comment]
Hi,
It looks like 'copy file' is not as fast as it need to be. Right now I am trying to copy a file from my local folder to compared folder but it is taking so much time. I think it is because after each copy folders are re-compared. But we just need to remove copied file from view to make it more efficient.

```
copyToFolder(uri: Uri, direction: 'to-compared' | 'to-me') {
    try {
      const [folder1Path, folder2Path] = pathContext.getPaths();
      const [from, to] =
        direction === 'to-compared' ? [folder1Path, folder2Path] : [folder2Path, folder1Path];
      const { root, dir, base } = path.parse(from);
      const pathWithoutSchema = dir.replace(root, '');
      const fileCopiedRelativePath = uri.fsPath.replace(pathWithoutSchema, '').replace(base, '');
      const fromPath = path.join(from, fileCopiedRelativePath);
      const toPath = path.join(to, fileCopiedRelativePath);
      copySync(fromPath, toPath);
      this.refresh(false);
    } catch (error) {
      log(error);
    }
  }
```

**Comment by moshfeu** [comment]
Thanks @noumanhabib, moved the discussion to https://github.com/moshfeu/vscode-compare-folders/discussions/175
