### ISSUE TITLE
confusing icons for take my file/take compared file

### ISSUE THREAD

**Issue by pvdhagen** [moshfeu/vscode-compare-folders#165]
When Compare Folders detects differences between files, I can click on the file and the differences are shown in a side-by-side view (if the windows is wide enough). The first folder selected ist called "my", the second one is "compared".
In the split-view, content of "my" is shown in the left panel, content of "compared is shown in the right panel.

There are two buttons to handle differences, "take my file" and "take compared file". In split-view, "take my file" equals to "copy the left view to the right view". Therefore, an icon with an arrow from left to right would meet my mental model.

It's the other way around. To take my file, which is shown on the left, the icon indicates movement from right to left.

From my perspective, that's extremely confusing. I'd like a setting to swap those icons.
I could change compared to be on the left side in the settings for better alignment, but I really like the "my" selection on the left.

![image](https://github.com/user-attachments/assets/a811a67d-a868-49fd-bb92-4915fbbef53d)

**Comment by moshfeu** [comment]
You're absolutely right
A fix is on its way
Thanks

**Comment by moshfeu** [comment]
Can you verify 🙏 ?

[compare-folders-0.25.1.vsix.zip](https://github.com/user-attachments/files/17482352/compare-folders-0.25.1.vsix.zip)
