### ISSUE TITLE
Enhance title to see left and right source

### ISSUE THREAD

**Issue by llgcode** [moshfeu/vscode-compare-folders#17]
it is difficult to know where the file comes from, it might be useful to have a title which indicates where the file comes from:
index.html (folder1) <-> (folder2)

**Comment by moshfeu** [comment]
If I understand you correctly, you can change that in the settings

![Screen Shot 2020-02-18 at 13 17 15](https://user-images.githubusercontent.com/3723951/74731636-09e43200-5251-11ea-8ddc-f50b4ce8e562.png)

Suggested at #13

**Comment by llgcode** [comment]
You might change the default settings ;-)

**Comment by moshfeu** [comment]
It's a big decision :)
Few more requests and I'll change.

**Comment by llgcode** [comment]
If I could suggest to switch left and right. I you look at changes in git extension for example: local content is always on the right. I'm always confusing when comparing folder that content of the current folder is on the left.

**Comment by moshfeu** [comment]
You can and I'll be happy to. Can you create an issue for that?
Also, it can be in settings too.
Want to do this?
