### ISSUE TITLE
Add menu in file explorer to compare a file present in another folder

### ISSUE THREAD

**Issue by llgcode** [moshfeu/vscode-compare-folders#19]
Compare File from Folder ...
If a setting exists with a list of related folders exists when executing "Compare File from Folder...", it will open a pickup list of related folder and compare the same file (if present) in that folder. 
I will be really useful!
I could provide you a PR if you need.

**Comment by moshfeu** [comment]
I'm not sure I understand the case but PRs are always welcome :)

**Comment by llgcode** [comment]
ok, I'll prepare it

**Comment by moshfeu** [comment]
Great

**Comment by moshfeu** [comment]
Following our discussion in #22, I'm closing it for now.
