### ISSUE TITLE
Have compare ignore filename capitalization

### ISSUE THREAD

**Issue by Hal47** [moshfeu/vscode-compare-folders#23]
Would it be possible to have an option for the process to be Capitalization-insensitive, so that it could compare, for example _C:\Help1\Capitalization.txt_ straight up with _C:\Help2\capitalization.txt_ ?

As is, the Compare treats both file with a single capitalization difference as completely different, unrelated things.

**Comment by moshfeu** [comment]
Good point. Thanks!

**Comment by moshfeu** [comment]
I'll love to get your feedback in the new (not published) version.

---------
1. Download [compare-folders-0.7.0.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/4265918/compare-folders-0.7.0.vsix.zip)
2. Unzip 
3. [install the .vsix file](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)

Thanks!

**Comment by Hal47** [comment]
Just tested it out comparing 330K+ files and it worked exactly as expected. Guess we can call this one done!

**Comment by moshfeu** [comment]
Thanks! Will publish it soon.

**Comment by moshfeu** [comment]
@Hal47 what's your Twitter username. I would be happy to mention you in the release tweet

**Comment by Hal47** [comment]
@moshfeu I don't link accounts from one site to another (all of them have different names, etc.) and you did all the work . . . so don't worry about that. Thanks for that quick fix though!

**Comment by moshfeu** [comment]
I announce about new versions on Twitter.  Like this: https://twitter.com/moshfeu/status/1234512381176434688?s=20.

I also like to give credit to whom give an idea (you in this case 😀)
But, as you wish.
