### ISSUE TITLE
Sometimes a click on file to diff also open the file in editor

### ISSUE THREAD

**Issue by yuvmel** [moshfeu/vscode-compare-folders#25]
Hi Mosh & thank you for making this free extension! :) I noticed a minor issue:
1. Opened 1st folder from VS menu, as usual.
2. Your icon appeared on sidebar (nice touch BTW) - opened 2nd folder from it.
3. Clicked on a common Jenkinsfile - both a diff + a new editor window to that file were opened.
4. I closed all windows & tried again - same behaviour.
5. Tried the same with another common file - .gitignore - only a diff window opened - seems OK.
6. Back to Jenkinsfile - same as `#3` above. EDIT: removed redundant issue link.

**Comment by moshfeu** [comment]
Thanks for the issue (and for the great review 😉)

Actually, I can't reproduce the issue

![video1](https://user-images.githubusercontent.com/3723951/79249185-942dc880-7e85-11ea-9b65-b941fec52ed7.gif)

Can you share your system info? (You can copy that from "About Visual Studio Code" menu)

**Comment by yuvmel** [comment]
I found the root cause - the [GroovyLint](https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint) extension tries to lint the `Jenkinsfile` & pops up a notification:
![image](https://user-images.githubusercontent.com/26660554/79271047-d5cf6b00-7ea7-11ea-946e-5daadad5fe2d.png)
Maybe it's related to how the diff window is opened? I'm not sure why the linter kicks in, but honestly - it's not that important, now that I know there's a reason - you may close this.

**Comment by moshfeu** [comment]
Thanks for the update. If you have any other features in your mind, I'll be happy to hear.
