### ISSUE TITLE
Feature Request:  Select both left and right folders

### ISSUE THREAD

**Issue by jlynchMicron** [moshfeu/vscode-compare-folders#26]
Is it possible to add a feature where you select both the left and right folders to compare?  I work on large projects and often only want to compare one sub folder with another sub folder.  It would be nice to do this without having to open up one of the folders I want to compare in a new window first.

**Comment by moshfeu** [comment]
Thanks for the issue.

Actually I've started to implement it several times but couldn't find the time to finish. I hope I'll have some time for this soon

**Comment by konrad-a** [comment]
+1
I need that feature too.

**Comment by moshfeu** [comment]
I've started to implement it. See attached PR.
I'd love to get your feedback about that version. If everything goes fine, I'll implement the rest.

**Comment by moshfeu** [comment]
v0.9.0 released!

v0.10.0 is on the way - includes select 2 sub folders to compare.
Please review the attached file in the new PR

**Comment by moshfeu** [comment]
v0.10.0 released. You're more than welcome to test and give feedback :)
Thanks!

**Comment by jlynchMicron** [comment]
@moshfeu just did a quick test run and it looks like it is working!  Thanks!

**Comment by moshfeu** [comment]
Thanks for the update, I'm glad to hear!
If you have more ideas for features, well.. you know what to do :)
