### ISSUE TITLE
Compare job never finishes

### ISSUE THREAD

**Issue by konrad-a** [moshfeu/vscode-compare-folders#27]
- Issue Type: `Bug`
- Extension Name: `compare-folders`
- Extension Version: `0.8.0`
- OS Version: `Darwin x64 19.4.0`
- VSCode version: `1.45.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 346,
		"activateCallTime": 5,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "moshfeu.compare-folders",
				"_lower": "moshfeu.compare-folders"
			},
			"activationEvent": "onView:foldersCompareAppService"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "ENOENT: no such file or directory, lstat '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/Versions'"
		},
		{
			"name": "Error",
			"message": "ENOENT: no such file or directory, lstat '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/Versions'"
		},
		{
			"name": "Error",
			"message": "ENOENT: no such file or directory, lstat '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Versions/Versions'"
		},
		{
			"name": "Error",
			"message": "ENOENT: no such file or directory, lstat '/System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/Versions'"
		}
	]
}
```

**Comment by konrad-a** [comment]
![image](https://user-images.githubusercontent.com/14833496/81502268-4a49ce00-92dd-11ea-893e-564394cb8360.png)

**Comment by moshfeu** [comment]
Can you elaborate about the folders you're trying to compare? for example, what their size? Because big folders (contains`node_module` for example) can cause such errors.
Or maybe other "special" case I can't think of right now..

**Comment by konrad-a** [comment]
I tried to compare 2 subdirectories within the same project.
So I opened a new project with the content of one subdirectory and compared it to the second subdirectory I selected.
They were not big - 41 files each.

**Comment by moshfeu** [comment]
I'm sorry. I don't know what to say. It feels like it's a system folders so maybe it's an issue with permissions or symbol links or something. Are you able to compare 2 other folders in a "normal" path (desktop for example)?

**Comment by moshfeu** [comment]
Hi @konrad-a . Is this issue still happening? If not, please close it. If yes, can you email me (moshfeu.dev@gmail.com)? I'd be happy to reproduce it with you and fix it. Thanks.

**Comment by konrad-a** [comment]
No, I was not able to repeat it any more.

**Comment by moshfeu** [comment]
Thanks!
