### ISSUE TITLE
Option to list files that are identical in the two folders

### ISSUE THREAD

**Issue by RodAtBurkeDataConsulting** [moshfeu/vscode-compare-folders#28]
When comparing two folders, it's good to (optionally) get feedback for files that are NOT different, i.e. identical

**Comment by moshfeu** [comment]
Interesting feature 👍

**Comment by moshfeu** [comment]
I pre-released [v0.11.0](https://github.com/moshfeu/vscode-compare-folders/releases/download/v0.11.0/compare-folders-0.11.0.vsix). Please install it and verify the feature is working as expected.
Thanks!

**Comment by RodAtBurkeDataConsulting** [comment]
That's working very well! - many thanks Mosh!
I would prefer the option to show identical files to be ON by default, but not something I would push for ... maybe there are reasons for having OFF as the default. cheers
