### ISSUE TITLE
doesn't work on ubuntu

### ISSUE THREAD

**Issue by MahdiHamidpour** [moshfeu/vscode-compare-folders#29]
There is no icon in left bar.

**Comment by moshfeu** [comment]
Thanks for letting me know. I'll check.

**Comment by moshfeu** [comment]
It's working for me. Want to try again? Maybe it solved in the newest version.
![VirtualBox_ubuntu_25_05_2020_00_45_07](https://user-images.githubusercontent.com/3723951/82765700-92aad500-9e21-11ea-9c7f-311ddfb75f2e.png)

**Comment by MahdiHamidpour** [comment]
hi dear.
it's work fine. It just my fault. Sorry.

Thank you for attention.

**Comment by moshfeu** [comment]
Great 😀
