### ISSUE TITLE
likely bug - missing new files

### ISSUE THREAD

**Issue by Zvika88** [moshfeu/vscode-compare-folders#36]
Hi Mosh, there seems to be a bug in CompareFolders. It does well when comparing files that exist on both sides, but If the first folder structure has new files added, and then you do compare to your old project before the change, then it will not show the new files missing.

BTW a feature we discussed on the other thread - Copy an entire file over - would be nice here too. I would even suggest doing the "copy file over" even ahead of the one-click copy change we discussed.

Best,
Zvika

**Comment by moshfeu** [comment]
I'm not sure I understand the issue. Are you comparing a folders against itself?
Can you describe the steps so I could reproduce the issue?

**Comment by Zvika88** [comment]
Hi Mosh,
I work on a project in two folder trees. One for staging and one for dev. The dev project is opened in Code. New files were created in the dev project tree as well as many other changes. I then want to integrate these changes into the staging project. While still in Code that has the dev project open, I call CompareFolders, "click to select a folder", I select the staging project tree for compare. I then get a tree list of differences between the trees.

Opening the tree and going down each file, CompareFolders show files from my dev tree (the one I was on to begin with) on the left side - these are the modified files, and the corresponding file before changes (from the staging tree) on the right side.   I can then copy manually the changes one by one.

**But new files that are in the dev project - are not shown in the diff tree**. That is the bug reported here. Only files that exist on both trees are shown in the compare result. You have to remember that there are new files and manually move them over.

Here BTW would be nice to have a "copy file over" button, both for new files and for over-writing and existing file because your new version that has too many changes and you just want them all in. 

BTW #2: another bug worth mentioning: There is a "Swap Sides" icon in the sidebar above the project tree. It does not work. When you click it, a small popup says "Source Refreshed", but nothing changes.

I hope that helps.

**Comment by moshfeu** [comment]
Unless I'm missing something, there are panels for "only in my folder" "only in compared" so new files should appear there. If you add new files after the comparison, you need to refresh.
If I didn't understand correctly, can we have a video chat so you could show me what you mean (or create a video that shows the issue.
Many thanks!

**Comment by Zvika88** [comment]
Hi Mosh, the new files are created before the comparison, yet they do not appear in the comparison results. Here is the exact sequence, step by step. I checked again and it happens every time:

1. Have a project tree, lets call it "staging".
2. Clone it to a new project, lets call it "dev".
3. Open "dev" in code. It has a "js" folder.  In the "js" folder, create a new file, let's say "newfile.js". Write something in it. Also, make changes to some other file in js, let's say "index.js"
4. Close all opened files from code. You are still in Code that has "dev" project open.
5. Select "CompareFolders" icon. In the side menu, it tells you to choose a folder to compare with. Select the "staging" project tree.
6. CompareFolers run and shows you the changes you made. The diff will show the js folder, and in it the changed index.js file.
7. The diff WILL NOT show that there is a newfile.js in the "dev" project that does not exist in the "staging" project. This is the reported bug. 

Please let me know if you still cannot repeat, I can do sequence of screenshots, or we can do it over the phone or something. I am in the Bay Area, California time zone.

Still, it is a great tool that you did. Even with this bug and few Code limitations, it is the reason I have abandoned IntelliJ/IDEA for Code. Kudos!

Thanks much,
Zvika

**Comment by moshfeu** [comment]
I've tried to reproduce the issue but couldn't. This is the result of comparing similar structures to what you described.

![Screen Shot 2020-06-07 at 8 36 07](https://user-images.githubusercontent.com/3723951/83961257-075a2680-a89a-11ea-8e1b-089878dd5096.png)

I'd glad to have a call with you. How can I contact you? (A Gmail account will be great. Or email me (moshfeu.dev@gmail.com)

> Still, it is a great tool that you did. Even with this bug and few Code limitations, it is the reason I have abandoned IntelliJ/IDEA for Code. Kudos!

Can't be more flattered 🤗

As usual, more suggestions are very welcome.

**Comment by Zvika88** [comment]
Hi Moshe,
In your screenshot there are 4 tabs: (1) Differences, (2) Only in my folder, (3) Only in compared folder, (4) identical files.  

Well, for whatever reason, in my CompareFolders there are no 4 tabs, just one section, which looks similar to your "Differences" tab, but is lacking the new files. I dont have the other tabs where new files should be shown. That obviously explains it. But how do I get this resolved?

Did I somehow get an old version of compare folders? It says that my version is 0.11.0 , which is I think is the latest on GitHub. Any ideas what am I missing?

Here is a screenshot of the sidebar that shows in my setup, that I just took with another project I am currently looking at. As I said - its just one section, similar to your "Differences" tab. There are no other tabs like "only in my folder" or "only in compared folder". 

<img width="299" alt="Screen Shot 2020-06-07 at 1 55 53 AM" src="https://user-images.githubusercontent.com/6226058/83964579-e2968c80-a862-11ea-8eca-1d14276ba64e.png">

**Comment by moshfeu** [comment]
It looks like a very old version (0.4.0), I'm not sure why you still get it. Maybe try to uninstall and re-install?
Are you using ubuntu?

**Comment by Zvika88** [comment]
no I am on a Mac, 10.14.6 Mojave, Code is up to date, and the extensions manager says that Compare Folders is version 0.11.0 . Very strange. See screenshot.

I uninstalled and re-installed it - no change, it behaves as before.

Mystery.

<img width="1072" alt="Screen Shot 2020-06-07 at 2 43 28 AM" src="https://user-images.githubusercontent.com/6226058/83965471-dad9e680-a868-11ea-9bd0-675446a17d45.png">

**Comment by Zvika88** [comment]
could it be the Node version (for Electron)? Mine is v10.15.3

**Comment by moshfeu** [comment]
Hard to believe but 🤷‍♂️
Mine is 
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (3 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
``` 

Try to install it from https://github.com/moshfeu/vscode-compare-folders/releases/download/v0.12.0/compare-folders-0.12.0.vsix..

**Comment by Zvika88** [comment]
My code reports exactly the same.

I installed from your vsix file, so now I am on 0.12.0 . However it still behaves the same, see screenshots:

<img width="347" alt="Screen Shot 2020-06-07 at 3 03 37 AM" src="https://user-images.githubusercontent.com/6226058/83965875-a582c800-a86b-11ea-9cbe-3bdc08a280f2.png">


<img width="348" alt="Screen Shot 2020-06-07 at 3 03 57 AM" src="https://user-images.githubusercontent.com/6226058/83965878-ac113f80-a86b-11ea-8581-84c203aedf6f.png">

**Comment by Zvika88** [comment]
<img width="422" alt="Screen Shot 2020-06-07 at 3 11 04 AM" src="https://user-images.githubusercontent.com/6226058/83966000-8d5f7880-a86c-11ea-9c10-e5f637985938.png">

**Comment by moshfeu** [comment]
This is SO weird, specially because the swap icon is there which added lately.
Maybe something in vscode configuration which prevent from rendering section.

Can you try with [insider](https://code.visualstudio.com/insiders/)

**Comment by Zvika88** [comment]
Removed VS code and all the extensions, cleaned all the preferences files. Re-installed Code and added only the Compare Folders extension - I now get the new version working. I think there might be a conflict with one of the other extension, if I learn more I'll report it. For now I am closing this bug report.

I still think that a "copy file over" command would be nice here. In the "DIFFERENCES" tab, when a file is selected , it will allow to copy file over from one side to the other, over-writing the other side's file. In the other tabs it will simply allow to copy the file to the other side.
