### ISSUE TITLE
Unable to select folder to compare

### ISSUE THREAD

**Issue by gvv5485** [moshfeu/vscode-compare-folders#4]
Issue Type: <b>Bug</b>

When I try to select click to select folder and select a folder it won't select one.

Just does nothing

Extension version: 0.0.5
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by moshfeu** [comment]
Thanks for the report! I'll check ASAP.

**Comment by moshfeu** [comment]
When you say `When I try to select click to select folder and select a folder it won't select one.`, are you meaning that when you clicked on the `Click to select folder` you saw the folder chooser dialog (I mean, something like [this](http://4.bp.blogspot.com/-ARuXw8FW_70/UU8Ab1NfZsI/AAAAAAAABn4/ak4T4q1B2Fg/s1600/JavaFX_DirectoryChooser.png))? Or you didn't saw anything?

**Comment by gvv5485** [comment]
I saw the dialogue, selected folder. It did nothing

**Comment by moshfeu** [comment]
Thanks!
Currently, the comparison result is presenting only the same files with different content but not files the exist in one folder but doesn't exist in the other.

For example:

Will be presented
_rootFolder/file.txt_ compare to _rootFolder2/file.txt_ 

Will not be presented
_rootFolder/anotherFolder/file.txt_ compare to _rootFolder2/file.txt_ 

Is this the case?
Anyway, you're right and the  extension need to show a message that not found to compare.

Thanks!
