### ISSUE TITLE
diffViewTitle setting is not working in OSX Version 1.46.0

### ISSUE THREAD

**Issue by iluvhk3000** [moshfeu/vscode-compare-folders#41]
I'm using VS Code with Version 1.46.0 in my Mac. I set my compareFolders setting as below

"compareFolders.excludeFilter": [
        "**/.DS_Store"
    ],
    "compareFolders.diffViewTitle": "compared path",

The setting excludeFilter can work properly but diffViewTitle has no effect to the view title, it's still showing nam only. Thanks.

![image](https://user-images.githubusercontent.com/53892940/84977326-a3b6df80-b15c-11ea-88b9-ee22b79eb0ae.png)

![image](https://user-images.githubusercontent.com/53892940/84977786-d57c7600-b15d-11ea-9be6-2d6f6ade3f44.png)

**Comment by moshfeu** [comment]
If I understand you correctly, `diffViewTitle` is affecting on the diff view title, not the files names in the tree view

For example:

`full path`

<img width="1180" alt="Screen Shot 2020-06-19 at 17 00 21" src="https://user-images.githubusercontent.com/3723951/85141013-caedd980-b24e-11ea-925c-8e9eead90a24.png">

vs

`name only`

<img width="1177" alt="Screen Shot 2020-06-19 at 17 04 11" src="https://user-images.githubusercontent.com/3723951/85141126-f40e6a00-b24e-11ea-9569-6bd52eb9a75c.png">

Is that what you mean?

**Comment by moshfeu** [comment]
Closing it for now. If it still reproduce, please comment or create a new one.
Thanks!
