### ISSUE TITLE
allow to copy file over from one side to the other in the split-view mode

### ISSUE THREAD

**Issue by Zvika88** [moshfeu/vscode-compare-folders#42]
When comparing different versions of the same project and you know that one of the sides is the relevant (newer) version, then instead of going over change by change (which could be lengthy), or instead of copy/paste all of one side over all of the other side (which still requires multiple key presses and clicks), allow for a one click action to copy from left to right or from right to left.

**Comment by moshfeu** [comment]
Thanks.
This is the territory of "Diff & Merge" because vscode API doesn't let to control the built-in diff view much.

Maybe it can be similar to #43 so files under the "DIFFERENCES" section will have 2 options: "copy My file to Compared" and the visa versa.

What do you think?

**Comment by Zvika88** [comment]
Hi Mosh, yes it is similar in that we want a file copied over, but here this copy needs to be available in the split view where files from both folders are shown side by side, while [#43](https://github.com/moshfeu/vscode-compare-folders/issues/43) has no split view, it is simply a file listed "only in" my folder or the compared folder. For [#43](https://github.com/moshfeu/vscode-compare-folders/issues/43) you can surely do with a drop-down menu from the file name. 

I guess having drop-down options (right menu click) from the file name such as: "copy from --> to " or "copy to <-- from"  (i.e. copy from left side to right side or the other way around) could address it in both cases. In the diff view we can have both options, but for the "Only in My Folder we will have only the  "copy from --> to " option (assuming the default layout sides) and for the "Only in Compared Folder" we will only have the  "copy to <-- from" option.

**Comment by moshfeu** [comment]
So, if I understand you correctly, what I suggested (2 option in right click or similar UI) looks ok to you, right?

**Comment by Zvika88** [comment]
Yes sure, that will be good enough and a big time saver for the user.

**Comment by Zvika88** [comment]
BTW one more reason to have a file copy option: Non-text files, such as images, fonts, video assets etc. One cannot edit them in the split view editor, so a file copy is the only way to get the correct version of such an asset into place.

**Comment by moshfeu** [comment]
As you might saw, I created an "insider" version of the extension to make the great testers (such yourself) much easier.
I'd love you to use the insider extension instead of the original (they can't work side by side).

The newest version already includes copy from and to "my folder".

https://marketplace.visualstudio.com/items?itemName=moshfeu.compare-folders-insider

Thanks!

**Comment by Zvika88** [comment]
Hi Mosh, the new version simply does not work. When choosing a project folder to compare with, nothing comes up. Instead, the top toolbar shows double icons as per the screenshot below. There is no diff or anything else shown. Sorry...
<img width="445" alt="Screen Shot 2020-07-10 at 5 39 08 PM" src="https://user-images.githubusercontent.com/6226058/87212664-95c82a80-c2d4-11ea-90b1-b9a91eb052db.png">

**Comment by Zvika88** [comment]
and also, Code becomes unstable and has to be restarted after that. Nothing else works. Tried few times - same thing.

**Comment by moshfeu** [comment]
Have you remembered to disable/uninstall the original extension?

> I'd love you to use the insider extension instead of the original (**they can't work side by side**).

**Comment by Zvika88** [comment]
thanks Mosh. Yep, that was it. Which explains BTW why I had double icons. Two plugins drawing them.
It now works, and the new functionality is cool!
I'll let you know more after using it for some time.

**Comment by moshfeu** [comment]
Thanks @Zvika88 . If you're not seeing a critical bug, I'll merge it and release it in the regular version.
In the next version I'll add also the context menu in the diff tree view (take my file / take compared file)

**Comment by Zvika88** [comment]
Hi Moshe, I cannot say about critical bugs yet because I only used it
briefly. I will not get to use it much for a few days, until our next
integration, which I am guessing will probably be by the end of the week or
so. From the little I saw it looks great, but as I said - it was just a
short use.

**Comment by Zvika88** [comment]
Hi Mosh,
The "copy to my folder" and "copy to compared folder" functions in the side menu, regarding files that exist only in one side, work well. But how do I copy over files that are in the split pane (diff) view? I cannot find the copy over command for these, is there such an option?

This option is required for many reasons. (1) For text files, one could do select-all, copy then select-all on the other side and paste. However, Code often screws up the indentation which results in a file that would always show as different, which is annoying. (2) If the file is not textual - for example, a new version of an image file - copy/paste would not help at all.

Copy over from one side to the other should also be available for files in the split-pane diff view mode. If it is there, can you please point me to it?

Otherwise, all looks great with the new version.

Thanks,
Zvika

**Comment by moshfeu** [comment]
You are right. This feature is not implemented yet. That's why the commit message is [partial 42] 😀 . This capability will be in 0.15.0 because I didn't wait for this to release the "copy to my" / "copy to compared" feature. I hope to release it next week. At least in the insider version.

Thanks for the update!
BTW, can I mention you in the next post on Linkedin / Twitter? I'd like to thank you publicly for your great contribution to this extension. (If so, please post your links)

**Comment by Zvika88** [comment]
Hi Mosh, no problems being mentioned, but my contribution is small. The credit is clearly all yours.

> Just a reminder, the feature is to add context menu also to the items in "difference" section ("Take my file", "Take compared file"). Dealing with the diff view is a headache because, sadly, the API in that area is missing important methods.

That will be just as useful. As long as the user can copy a file over - any file, even an image or font - then by all means, if it is easier this way then do it in the "difference" section. 

Best,
Zvika

**Comment by moshfeu** [comment]
I believe that it will support all the files types (at least what [`copySync`](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/copy-sync.md) supports).

You ideas are valuable and contribute to that extension! May I have your Linkedin / Twitter / both profile url? Thanks :)

**Comment by Zvika88** [comment]
https://www.linkedin.com/in/zvi-eintracht/
https://twitter.com/ZEintracht

**Comment by Zvika88** [comment]
Hi Mosh,
Besides "copy" from one side to the other in the "only in my folder" and "only in compared folder",  it can also be nice to have a "remove this file" option which will delete a file. Sometimes, during integration, you find that you accumulated assets that are no longer needed, for example, an icon or image that is no longer in use. The compare function would be a convenient place to find and remove such leftovers.

Cheers,
Zvika

**Comment by moshfeu** [comment]
Nice idea! Moved to a new issue.

**Comment by moshfeu** [comment]
I've released 0.15.0 insider with this feature.
Can you give a shot? Thanks!

**Comment by Zvika88** [comment]
"Take my File", "Take compared File" seems to work perfectly, thanks!

You surely have seen the many times that Code screws up indentations when copying up content via copy/paste, which is especially annoying if the files should be the same and the entire file is copied over,. It is resulting in that file always showing up in the diff (with that white spaces message). Over time the list of such white-space only diffs grows.

Well, with this new feature, that annoying phenomenon can be easily fixed, cool!

**Comment by moshfeu** [comment]
Thanks for the fast feedback!

**Comment by Zvika88** [comment]
Quick question/suggestion: After doing a "Take my file" action, there is a "Source refreshed" popup at the bottom right of the screen. It pops up after every file. Can you programmatically close it after ~3 seconds? 

When going over a large list of files on the side menu (always top left side of the screen, as the diff list gets refreshed and copied files are removed from the list), then after every action having to go to the lower right side to close the popup, and continue back and forth diagonally across the screen -  well, you get the point...
