### ISSUE TITLE
allow to copy a file that is "only in my folder" to the compared folder, and vise versa

### ISSUE THREAD

**Issue by Zvika88** [moshfeu/vscode-compare-folders#43]
If your newer project instance has some new files, then as of now you need to copy the new files over in another app like the Finder. You have to switch from Code to Finder, open a second Finder window, navigate on both, and copy from the proper place in one Finder to the other. Instead, it would be much more convenient to have a side menu dropdown command inside Code / Compare Folders to allow such files to be copied over, in their correct relative path, to the other folder tree.  

It should be available both from "my Folder", i.e. allow to copy a file that is "only in my folder" to the compared folder (but keep its relative position and create folders if needed), and from the "compared folder", i.e. allow to copy a file that is "only in compared folder" to my folder.

After the copy it will, of course, disappear from the "only in" section, and will not need to be shown in the diff section because that content would be identical.

**Comment by moshfeu** [comment]
Thanks!

**Comment by moshfeu** [comment]
Actually this is solved in #44
