### ISSUE TITLE
Allow deleting file

### ISSUE THREAD

**Issue by moshfeu** [moshfeu/vscode-compare-folders#45]
Besides "copy" from one side to the other in the "only in my folder" and "only in compared folder",  it can also be nice to have a "remove this file" option which will delete a file. Sometimes, during integration, you find that you accumulated assets that are no longer needed, for example, an icon or image that is no longer in use. The compare function would be a convenient place to find and remove such leftovers.

Cheers,
Zvika

_Originally posted by @Zvika88 in https://github.com/moshfeu/vscode-compare-folders/issues/42#issuecomment-661655684_

**Comment by moshfeu** [comment]
@Zvika88 the feature is available in [0.16.0-insider](https://marketplace.visualstudio.com/items?itemName=moshfeu.compare-folders-insider).
What do you think?

**Comment by Zvika88** [comment]
Hi Mosh, cool, the delete works fine. I have removed the current and switched to using the new version instead, and will let you know if I encounter any issue with any aspect of its functionality.

**Comment by moshfeu** [comment]
Thanks 👍
