### ISSUE TITLE
Can you programmatically close "Source Refreshed" notification after ~3 seconds?

### ISSUE THREAD

**Issue by moshfeu** [moshfeu/vscode-compare-folders#48]
After doing a "Take my file" action, there is a "Source refreshed" popup at the bottom right of the screen. It pops up after every file. Can you programmatically close it after ~3 seconds? 

When going over a large list of files on the side menu (always top left side of the screen, as the diff list gets refreshed and copied files are removed from the list), then after every action having to go to the lower right side to close the popup, and continue back and forth diagonally across the screen -  well, you get the point...

_Originally posted by @Zvika88 in https://github.com/moshfeu/vscode-compare-folders/issues/42#issuecomment-665299866_

**Comment by moshfeu** [comment]
@Zvika88
Just published 0.15.1 insider. Please check it out.

**Comment by Zvika88** [comment]
It is working great, thanks for the extraordinarily fast response!
