### ISSUE TITLE
Glob matching is case sensitive on Windows

### ISSUE THREAD

**Issue by SamMackrill** [moshfeu/vscode-compare-folders#49]
Exclude/Include filters should be case insensitive on Windows

**Comment by moshfeu** [comment]
There is a configuration option to ignore / not ignore case in files name - `compareFolders.ignoreFileNameCase`


![video1](https://user-images.githubusercontent.com/3723951/89118450-9e181d80-d4ae-11ea-82c9-f0c5023a1811.gif)

**Comment by SamMackrill** [comment]
Cool, thanks. Perhaps this should default to on for windowz?

**Comment by moshfeu** [comment]
It's a nice idea. I'll ask the community what they think should be default. Hope they will answer :)
https://www.linkedin.com/posts/moshfeu_comparefolders-activity-6698302120094957568-AA5t

**Comment by moshfeu** [comment]
Democracy is winning :)
