### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by seoriy** [moshfeu/vscode-compare-folders#50]
- Issue Type: `Performance`
- Extension Name: `compare-folders`
- Extension Version: `0.15.2`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: [`1.47.3`]

[moshfeu.compare-folders-unresponsive.cpuprofile.txt](https://github.com/moshfeu/vscode-compare-folders/files/5022634/moshfeu.compare-folders-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by moshfeu** [comment]
Thank you for reporting this!

Is your project has a lot of files?
Can you make sure [`compareFolders.excludeFilter`](https://github.com/moshfeu/vscode-compare-folders#options-under-vscode-settings) configuration excludes the plugins / libraries / modules folder (e.g. `node_modules`)
