### ISSUE TITLE
The Compare Folder 0.15.2 does not work with the VS Code latest version 1.48.0 (user setup)

### ISSUE THREAD

**Issue by abhisit** [moshfeu/vscode-compare-folders#52]
Your tool is really helpful to help me re-base/merge my code, thank you so much!

And upon yesterday, I am updating my VS Code to the latest version 1.48.0 (user setup) on my Windows 10 with Remote - SSH 0.51.0 on Linux and the Compare Folder 0.15.2, I have been tried to run "Remote - SSH: Kill VS Code Server on Host..." on the Linux and re-open my Windows VS Code and it does not work.

I am choosing the folder to compare and not things show, message, compare windows... It just disappeared. 

Update
=====
Run from the command is work.
![image](https://user-images.githubusercontent.com/3991182/90729221-6f90a400-e2f0-11ea-9252-9bb4e72a61cb.png)

And when click on the menu does not work.
![image](https://user-images.githubusercontent.com/3991182/90729286-8c2cdc00-e2f0-11ea-9861-7e05549a73e6.png)

**Comment by moshfeu** [comment]
Interesting. Actually, I never used vscode with remote.
I'm not sure I have a time in the next week.
Can you try using vscode insider? Or an older version of the extension?

**Comment by abhisit** [comment]
I have been installed the VS Code Insider version 1.49.0 (user setup) with the Compare Folder 0.15.2 and it does not work as well the same.

**Comment by moshfeu** [comment]
This is weird because `click to select folders` calls the same command as the command palette. Unfortunately, I don't have the required platforms to reproduce the issue. 
If anyone can reproduce and debug it, that will be great!
