### ISSUE TITLE
Allow folders to compare to be set on vscode settings

### ISSUE THREAD

**Issue by orellabac** [moshfeu/vscode-compare-folders#55]
I really like this extension, but everytime I close vscode I need to reset the folders to compare. It will be great if I could save the folders to compare on my settings file

**Comment by moshfeu** [comment]
Thanks for the idea.
Do you mean that the extension will always will be initiate with the same 2 folders from settings? Or you mean sort of favorites list so there will be a quick pick list of them?
If the second option, this feature is kinda exists. See https://github.com/moshfeu/vscode-compare-folders#how-to-use - `From history`

**Comment by orellabac** [comment]
Thanks, I meant more the option to setup two folders in the settings so
each time I start my IDE it uses them.

I forked your project and notice that you can do the same with an
environment variable but that did not match my needs. I just added a
folderLeft and folderRight option. I can do a PR with those changes if you
think that is something some other people might find useful

**Comment by moshfeu** [comment]
I'd love to see it.
The only concern I have here that usually developers have more than one environment so they might want a **list** of pair folders.
Have you tried to use the `From history` feature?

**Comment by orellabac** [comment]
I had not tried the From history

in my case I just want it to read my folder setting from the local
.vscode\settings.json file.
Usually I have of reference files that I just want to compare with and I am
not usually comparing with other folders.

**Comment by moshfeu** [comment]
Well, it can't harm anyway, so why not? :)
Please create a PR and we'll continue from there..
