### ISSUE TITLE
Ignore extension when comparing files

### ISSUE THREAD

**Issue by orellabac** [moshfeu/vscode-compare-folders#57]
I have this scenario:

I am doing code migrations, and usually I would like to compare old code with new code.
If for example I am migrating from Visual Basic to C# files are .vb and .cs is there a way to ignore the extension 
I would like to have the side by side

**Comment by gliviu** [comment]
Added a new option for custom name comparison. 

```js
var dircompare = require('dir-compare');
var path = require('path')

var options = {
    compareSize: false,                    // compare only name by disabling size and content comparison
    compareContent: false,
    compareNameHandler: customNameCompare, // name comparison that ignores extensions
    ignoreExtension: true,                 // this option is supported by the custom name compare below
};

function customNameCompare(name1, name2, options) {
    if (options.ignoreCase) {
        name1 = name1.toLowerCase()
        name2 = name2.toLowerCase()
    }

    if (options.ignoreExtension) {
        name1 = path.basename(name1, path.extname(name1))
        name2 = path.basename(name2, path.extname(name2))
    }
    return ((name1 === name2) ? 0 : ((name1 > name2) ? 1 : -1))
}

var path1 = '/tmp/a';
var path2 = '/tmp/b';

dircompare.compare(path1, path2, options).then(res => {
    res.diffSet.forEach(dif => console.log(`${dif.name1} ${dif.name2} ${dif.state}`))
})

// Outputs
// icon.svg icon.png equal
// logo.svg logo.jpg equal
```

For reference the default name comparison can be found in [defaultNameCompare.js](https://github.com/gliviu/dir-compare/blob/24/src/nameCompare/defaultNameCompare.js).

Until I publish you can install this branch with `npm install gliviu/dir-compare#24`.

Let me know if something missing.

**Comment by moshfeu** [comment]
This was fast, thank you @gliviu!
I'll implement it and let you know.

**Comment by moshfeu** [comment]
It's working nice. 
Although, now, when I think about it, it's a risky feature.
Consider one folder with _main.html_ and _main.js_, and other folder with _index.css_ and _index.php_? Which of them should be compared?
What do you think @orellabac?

**Comment by moshfeu** [comment]
I've been thinking about a more accurate solution. `ignoreExtension` option (in the extension) will be an array of pairs of extensions (e.g. `['js', 'ts']`). The this extension will ignore the files extension only if both of them are a pair in `ignoreExtension` list. Something list this:


```ts
if (options.ignoreExtension) {
  if (
    options.ignoreExtension.some((exts: [string, string]) => {
      return exts.includes(extnameOnly(name1)) && exts.includes(extnameOnly(name2));
    })
  ) {
    name1 = path.basename(name1, path.extname(name1));
    name2 = path.basename(name2, path.extname(name2));
  }
}
```

**Comment by orellabac** [comment]
I like that approach! yes that will work perfectly and avoid nasty errors

**Comment by gliviu** [comment]
[v2.4.0](https://www.npmjs.com/package/dir-compare/v/2.4.0) is now published with new option and some minor tweaks.

**Comment by moshfeu** [comment]
I've created a PR with this feature. Please give it a try - https://github.com/moshfeu/vscode-compare-folders/files/5541183/compare-folders-0.19.0.vsix.zip (extract the zip and [install the .vsix file](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix))

Thanks

**Comment by orellabac** [comment]
I gave it a try but I do not know what I am doing wrong:

![image](https://user-images.githubusercontent.com/4247006/99160782-62e1d900-26b0-11eb-8087-fe772fb6e853.png)

I am comparing a bteq file against a py file but it does seem to match them.

**Comment by moshfeu** [comment]
@orellabac 

It should be 

```json
"compareFolders.ignoreExtension": [
  ["bteq", "py"]
],
```

**Comment by moshfeu** [comment]
Still blocked because of https://github.com/gliviu/dir-compare/issues/25
