### ISSUE TITLE
Add the possibility to ignore spaces or moves within the files

### ISSUE THREAD

**Issue by An-De** [moshfeu/vscode-compare-folders#59]
Comparing files, a lot of differences and false positives are signaled. 
Most of these cases are related to spaces (either leading or trailing) or in another example, rows that are equal but in different positions.
Some additional settings to manage those situations will be very helpful and appreciated.
To help the developers to figure out and better understand this type of problem, try to use Compare plugin in Notepad++ (https://github.com/jsleroy/compare-plugin)

**Comment by moshfeu** [comment]
The feature is ready for testing.
Please [download](https://github.com/moshfeu/vscode-compare-folders/files/5726352/compare-folders-0.20.0.vsix.zip) it (you can also find it in the PR) or download the insider version from the [App Market](https://marketplace.visualstudio.com/items?itemName=moshfeu.compare-folders-insider) (you will need to deactivate the original).

I'd love to get your feedback.
Thanks!

**Comment by An-De** [comment]
Hi Mosh,
it seems now it's working better 👍 
See the screenshot below (the second one with the new enabled settings - white spaces and end of line)

![image](https://user-images.githubusercontent.com/63411202/102866463-96deb580-4437-11eb-9e0e-886244a5f6ce.png)
![image](https://user-images.githubusercontent.com/63411202/102866762-166c8480-4438-11eb-975b-16630a6d7f17.png)

Thanks!

**Comment by moshfeu** [comment]
I'm so happy to hear (and see my job on someone else's screen 😄)!
I'll give the insider version few mire days then I'll publish the original one.

Thanks!
