### ISSUE TITLE
Poor icon visibility on Dark+ theme

### ISSUE THREAD

**Issue by gjsjohnmurray** [moshfeu/vscode-compare-folders#6]
When the row is selected:
![image](https://user-images.githubusercontent.com/6726799/69141851-7e2a0080-0abd-11ea-9ba9-b7160d17095b.png)

When unselected:
![image](https://user-images.githubusercontent.com/6726799/69141913-9ac63880-0abd-11ea-8f00-8bb2b758bee3.png)

**Comment by moshfeu** [comment]
Thank you!
