### ISSUE TITLE
"Copy to [folder]" is copying the whole directory tree, not just the file

### ISSUE THREAD

**Issue by graememeyer** [moshfeu/vscode-compare-folders#61]
I'm using Extension v0.20.0 with VSCode 1.52.1 on W10 1909/18363.1256.

If I compare two folders:

C:\Users\username\Desktop\temp\1
    C:\Users\username\Desktop\temp\1\file 1.txt

C:\Users\username\Desktop\temp\2
    C:\Users\username\Desktop\temp\2\file 1.txt
    C:\Users\username\Desktop\temp\2\file 2.txt

In the CompareFolders UI in VSCode:
![image](https://user-images.githubusercontent.com/3931530/104320906-d51d4100-54da-11eb-9918-caeec5a1da17.png)

If I right-click on file two and select "Copy to My Folder", it copies an entire `Users\username\Desktop\temp\2\file 2.txt` structure to the \temp\1 directory, like so:

![image](https://user-images.githubusercontent.com/3931530/104321080-0d248400-54db-11eb-849d-4bc29adb9fa6.png)

This happens in both directions, e.g. if there is a new file in "my" folder, and I copy it to the compared folder, get the same incorrect folder structure.

**Comment by moshfeu** [comment]
Hi Graeme,
Thanks for letting me know, I'll check the issue.

**Comment by moshfeu** [comment]
mac / windows incompatibility 🤯
I think I fixed this.
There was another bug on Windows with Recent Compared. Ideally, when you chose pair of folders it stored, so later on you can choose from this list. The bug caused the store mechanizm to store broken paths over and over. Can you verify that this is working well too? Don't forget to run `> Compare Folders: Clear recent compares`.

Thanks!

[compare-folders-0.20.1.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/5826881/compare-folders-0.20.1.vsix.zip)

**Comment by graememeyer** [comment]
This seems to have fixed the problem. I ran it through a few different tests with nested folders, tried copying in both directions and all went as expected. Thank you! 

Minor note, when I deleted the last differing file, I got this message:

> [Compare Folders] There are no differences in any file at the same path.

Which I found confusing the first couple of times. I guess the delete action triggers a re-scan for file differences, which generated this message because there were none left. It was a little confusing because there were a few previous stacked messages and I thought something had broken. I checked manually, and re-ran it a couple of times and everything is working as it should though. A small change to the message might be helpful - something like "the compared folders are now synchronized".

**Comment by moshfeu** [comment]
I like your idea! It's better to be positive anyway so instead of being sad because `There are no differences in any file at the same path.` I've changed the icon and took your sentence `The compared folders are synchronized`.

<img width="374" alt="Screen Shot 2021-01-18 at 22 41 18" src="https://user-images.githubusercontent.com/3723951/104961303-b9380480-59de-11eb-8fce-7efa9c4b2d61.png">

[compare-folders-0.20.1.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/5832335/compare-folders-0.20.1.vsix.zip)

**Comment by moshfeu** [comment]
Published 👍
