### ISSUE TITLE
Extension doesn't save changes in simbolic links

### ISSUE THREAD

**Issue by gnuton** [moshfeu/vscode-compare-folders#62]
Hi,
Fist of all thanks for this magnificent plugin!
Yesterday btw I noticed that the  compare folders extension shows correctly symbolic links in the sidebar, allows to edit them but when I try to store them then it fails.
Ideally:
- symbolic links should be displayed in the side bar with a different icon (if possible)
- Editing the file should be allowed if vscode can sucessfully store the changes.

**Comment by moshfeu** [comment]
Thanks for the issue!
I'll see what I can.

**Comment by moshfeu** [comment]
> but when I try to store them then it fails.
What do you mean by "store" them?

Can you describe the specific steps I should to reproduce the issue?
Can you also specify your OS?

Thanks

**Comment by gnuton** [comment]
I am using linux, but I guess any Unix like is will be affected
