### ISSUE TITLE
Ignore all whitespace differences

### ISSUE THREAD

**Issue by jwarkentin** [moshfeu/vscode-compare-folders#65]
I'm in desperate need of the ability to do some diffs on some project directories that *should* be very similar but have a lot of whitespace differences scattered around, making it impossible to easily figure out what's meaningfully different between them. Any chance you might be able to add something equivalent to running `diff -b` or `diff -w`?

For the record, I have the `ignoreWhiteSpaces` option set which does ignore some whitespace differences like those at the start or end of a line, but that's it. It still shows differences in the number of newlines or whitespace differences in the middle of a line, like between a bracket and a comment.

**Comment by moshfeu** [comment]
Thanks for the issue (and sorry for the late response).
This extension is built on top of [dir-compare](https://github.com/gliviu/dir-compare) library.

I'll open an issue there and see what the maintainer says

**Comment by gliviu** [comment]
I'm thinking to add a new option `ignoreAllWhiteSpaces` which will basically remove every white space and compare contents. This will be similar to `diff -w`.

**Comment by gliviu** [comment]
Should be ready now. I added two more options - (1) ignore all white spaces and (2) ignore empty lines.
```
ignoreLineEnding      Ignore crlf/lf line ending differences
ignoreWhiteSpaces     Ignore white spaces at the beginning and ending of a line (similar to 'diff -b')
ignoreAllWhiteSpaces  Ignore all white space differences (similar to 'diff -w')
ignoreEmptyLines      Ignores differences caused by empty lines (similar to 'diff -B')
```

**Comment by moshfeu** [comment]
Thanks!
I'll implement it as soon as I'll have a second to breathe :)

**Comment by moshfeu** [comment]
Just deployed it in the latest version of the insider version.
I'd be happy if you can check it (don't forget that both of extensions can't run at the same time so deactivate the regular one before you install the insider version)

**Comment by moshfeu** [comment]
Published
