### ISSUE TITLE
Close and Reopen Comparison

### ISSUE THREAD

**Issue by matheusmpupo** [moshfeu/vscode-compare-folders#68]
Hello there! I hope you are doing well
First of all, thank you for this amazing plugin!

I've installed this plugin earlier this week and a feature that I really miss and would very much like it to be added is the comparison to be saved and reloaded when VSCode is closed and reopened.

I think that a good way to do that is by saving the two compared folder path with the last file opened in editor and when VSCode is reopened the comparison is redone. At least, this way seems better than saving all the comparison result.

At the moment, what happened when I try to reopen comparison is that VSCode crashes and a new project is needed in order to continue.

**Comment by moshfeu** [comment]
I'm really glad to hear you like it 😀

For the idea, do you mean that vscode will open show the compared files on startup? If so, seems like vscode already do this (on mac at least) - when you reopen a folder it shows the last diff view (screen record attached).

About the extension to "remember" the paths, the extension has history list so you can open a pair comparison from [recent compares](https://github.com/moshfeu/vscode-compare-folders#how-to-use) list.

I wonder what should be the logic of comparing the last paths. What if it's a different folder? What if those are sub folders? What if the user comparing 2 different folders regardless the one (or more) in the workspace?

What do you think?

**Comment by matheusmpupo** [comment]
Maybe the problem is in Windows or even at my own computer, since Visual Studio crashes if I try to reopen :(
Thanks for your reply, I will make a few more tests
