### ISSUE TITLE
Nothing happens after selecting folder

### ISSUE THREAD

**Issue by gjsjohnmurray** [moshfeu/vscode-compare-folders#7]
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

1. Open a folder in VS Code
2. Switch to the extension in Activity Bar
3. Click on 'Click to select folder'
4. Choose a random folder in the Windows selector dialog and click 'Open'
5. Nothing appears under the 'Click to select folder' row.

**Comment by moshfeu** [comment]
Thank you!
The thing is that when the compared folder's structure is different there are no files to compare due it compares only files with the same relative path. See [#notice](https://github.com/moshfeu/vscode-compare-folders#notice).

I've also added a notification for that:

<img width="582" alt="Screen Shot 2019-11-21 at 7 58 18" src="https://user-images.githubusercontent.com/3723951/69310190-b6a01a80-0c34-11ea-82dd-97ee9c2314da.png">

But seems that it's not clear either. So, I'm also adding a message in the panel itself that saying the same:

<img width="297" alt="Screen Shot 2019-11-21 at 7 59 30" src="https://user-images.githubusercontent.com/3723951/69310793-e3ecc880-0c34-11ea-8f32-62fb01ba7e5f.png">

Make sense?
