### ISSUE TITLE
Issue regarding non-redable files

### ISSUE THREAD

**Issue by joscarras** [moshfeu/vscode-compare-folders#71]
Hello!

This is such a great and useful plugin! 

The only issue I have is that when I compare folders (using the VS-Code remote development plugin) that have files that are not readable by the user it crushes and does not display anything.

Is it possible to somehow handle the error and let the diff complete?

![image](https://user-images.githubusercontent.com/5412596/111276202-c28cc880-863f-11eb-970d-9d6272e4026f.png)

**Comment by moshfeu** [comment]
Thanks, I'm really happy you like it.
Unfortunately, I have no experience nor a technical environment to test it (I probably can create an account on Azure etc but I'm not sure I have time for that).

Can you go to the OUPUT tab and select "Compare Folders" and share the output if relevant?

<img width="766" alt="Screen Shot 2021-03-16 at 10 51 29" src="https://user-images.githubusercontent.com/3723951/111281421-96744600-8645-11eb-8649-7c3db870b4d2.png">

**Comment by joscarras** [comment]
Hey Thanks!

You can reproduce this issue in your local computer (I am using Linux)

```
mkdir -p tmp/test1/test1.good
mkdir -p tmp/test2/test2.good
mkdir -p tmp/test1/test1.bad 
mkdir -p tmp/test2/test2.bad
touch tmp/test1/test1.good/test.txt
touch tmp/test2/test2.good/test.txt
touch tmp/test1/test1.bad/test.txt
touch tmp/test2/test2.bad/test.txt
sudo chown root:root tmp/test2/test2.bad/ -R
sudo chmod og= tmp/test2/test2.bad/
```

Then if you do the compare you will see this:

![image](https://user-images.githubusercontent.com/5412596/111287502-f40b9100-864b-11eb-9e93-b2ff28288517.png)

**Comment by moshfeu** [comment]
Thanks 👍
I'll work on it

**Comment by joscarras** [comment]
No, THANK YOU for this great plugin!

I am actually sorry for not being able to fix / help you fix this at this time!

**Comment by moshfeu** [comment]
Sorry for the late response :|
I'm not sure how to do it with mac, I have only one user.
Anyway, it seems the relevant piece is in the (great) [dir-compare](https://github.com/gliviu/dir-compare#use) library.
Can you try to test the comparison using its cli? If it reproduced, we can create an issue there.

Thanks

**Comment by joscarras** [comment]
Hello! Np!!! Have been very busy my self!

You are right, I got the error from the dir-compare-cli. Here is how to reproduce:


```
mkdir -p tmp/test1.good
mkdir -p tmp/test2.good
mkdir -p tmp/test3.bad
touch tmp/test1.good/test.txt
touch tmp/test2.good/test.txt
touch tmp/test3.bad/test.txt
sudo chown root:root tmp/test3.bad/ -R
sudo chmod og= tmp/test3.bad/
cd tmp/
npm install dir-compare-cli
```
`./node_modules/.bin/dircompare test1.good test2.good`

Entries are identical
total: 1, equal: 1, distinct: 0, only left: 0, only right: 0

`./node_modules/.bin/dircompare test1.good test3.bad`

Error occurred: Error: EACCES: permission denied, scandir '/home/joseph/tmp/test3.bad'
    at Object.readdirSync (fs.js:981:3)
    at getEntries (/home/joseph/tmp/node_modules/dir-compare-cli/node_modules/dir-compare/src/compareSync.js:18:26)
    at compare (/home/joseph/tmp/node_modules/dir-compare-cli/node_modules/dir-compare/src/compareSync.js:33:20)
    at Object.compareSync (/home/joseph/tmp/node_modules/dir-compare-cli/node_modules/dir-compare/src/index.js:27:5)
    at /home/joseph/tmp/node_modules/dir-compare-cli/src/cli/dircompare.js:113:44
    at new Promise (<anonymous>)
    at run (/home/joseph/tmp/node_modules/dir-compare-cli/src/cli/dircompare.js:112:38)
    at Object.<anonymous> (/home/joseph/tmp/node_modules/dir-compare-cli/src/cli/dircompare.js:147:1)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)`

How do you want to proceed?

**Comment by moshfeu** [comment]
Thank you for the detailed comment!
I opened an issue in dir-compare repo. Please subscribe this issue to track the progress (and give more info if needed).

**Comment by gliviu** [comment]
> Is it possible to somehow handle the error and let the diff complete?

There is not much dir-compare can do if it does not have permissions to read a folder (test3.bad in our example).
Even if it ignores the forbidden entries, returning any kind of result would be meaningless because it does not account for the skipped entries.

> it crushes and does not display anything.

It actually displays the generic 'Oops, something went wrong while comparing' message.
And the user should go into Output -> Compare Folders to find the reason.

I'm not sure if that's enough. @moshfeu should know if the exception handling can be improved in this case.

**Comment by joscarras** [comment]
@gliviu hello and thank you for the great plugin (dir-compare) and your asistance!

Ideal would be to do what Meld does

![image](https://user-images.githubusercontent.com/5412596/115349439-86a7ce80-a1bc-11eb-8606-3e8cb94a4499.png)

This gives the users the ability to at least see the rest of the files and give a clear indication why that folder was not comparable.

Would it be possible to add an option in dir-compare to handle error like that and just report the files different?

**Comment by gliviu** [comment]
Yes it is. I remember we approached broken symlinks in a similar way.
When two files are different there is a [reason](https://gliviu.github.io/dc-api/interfaces/difference.html#reason) field indicating what caused the difference.
I will add another value such as `permission-denied`.

**Comment by moshfeu** [comment]
Thanks @gliviu!
Do you know how I can reproduce the issue on mac with only 1 user? Is there another way to get `permission-denied`? So I could test it and adjust the UI to handle it.

**Comment by joscarras** [comment]
Thank @gliviu and @moshfeu for your assistance!

@moshfeu  can you try this on your mac and let me know if you get the error?

```
mkdir -p tmp/test1.good
mkdir -p tmp/test2.good
mkdir -p tmp/test3.bad
touch tmp/test1.good/test.txt
touch tmp/test2.good/test.txt
touch tmp/test3.bad/test.txt
sudo chmod -rxw tmp/test3.bad/
```

To delete the tmp folder this should work

`sudo rm tmp -rf`

Let me know!

**Comment by moshfeu** [comment]
Yes! Thank you.

**Comment by gliviu** [comment]
I'll let you know when it's done. Probably somewhere at the end of next week.

**Comment by gliviu** [comment]
I have published 3.2.0 including the option to handle permission denied errors.
Details about this option can be found in [Options.handlePermissionDenied](https://gliviu.github.io/dc-api/interfaces/options.html#handlepermissiondenied).

One remark though. `dir-compare does` not report anything about the root folders. If I'm comparing `test1.good` and `test3.bad` it will not report `test3.bad` as having permission denied. Instead all files inside `test3.bad` will be  reported as missing.

For this reason I suggest that `vscode-compare-folders` checks the permissions of root folders and reports them properly.
Here is the code for checking permissions with node:

```javascript
const fs = require('fs')

function hasPermissionDenied(entryPath) {
	try {
		fs.accessSync(entryPath, fs.constants.R_OK)
		return false
	} catch {
		return true
	}
}

```

**Comment by joscarras** [comment]
Hey @gliviu thank you very much! Highly appreciate all your hard work in this!!!

**Comment by moshfeu** [comment]
> I have published 3.2.0 including the option to handle permission denied errors.
> Details about this option can be found in [Options.handlePermissionDenied](https://gliviu.github.io/dc-api/interfaces/options.html#handlepermissiondenied).
> 
> One remark though. `dir-compare does` not report anything about the root folders. If I'm comparing `test1.good` and `test3.bad` it will not report `test3.bad` as having permission denied. Instead all files inside `test3.bad` will be reported as missing.
> 
> For this reason I suggest that `vscode-compare-folders` checks the permissions of root folders and reports them properly.
> Here is the code for checking permissions with node:
> 
> ```js
> const fs = require('fs')
> 
> function hasPermissionDenied(entryPath) {
> 	try {
> 		fs.accessSync(entryPath, fs.constants.R_OK)
> 		return false
> 	} catch {
> 		return true
> 	}
> }
> ```

@gliviu you're awesome! I'll bump the version and add the permission check for root folders.

**Comment by moshfeu** [comment]
@joscarras I've just made a new version (0.22.0).
As @gliviu suggested, in case of root folder or a subfolder is not accessible the extension shows a message.

Can you test it please?
Thanks!

[compare-folders-0.22.0.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/6455195/compare-folders-0.22.0.vsix.zip)

**Comment by joscarras** [comment]
@moshfeu  and @gliviu  thank you both so much! It works perfect! And can now compare what is comparable and even get the notification for what folders had access issues!

I think we can close this!

Thank you both so much!
