### ISSUE TITLE
Modify activation events for extension

### ISSUE THREAD

**Issue by vchirikov** [moshfeu/vscode-compare-folders#73]
Hello, first of all thanks for your work!

I noticed that the extension is always in the loaded state, even if I don't use it.
Maybe we can change [activation events](https://code.visualstudio.com/api/references/activation-events#Start-up) to save some resources on vs code startup?

**Comment by moshfeu** [comment]
Sorry for the delay 😅
It's a good point. I guess I can use [`onStartupFinished`](https://code.visualstudio.com/api/references/activation-events#onStartupFinished). What do you think?

**Comment by moshfeu** [comment]
resolved by https://github.com/moshfeu/vscode-compare-folders/commit/788f8cb8698efbb443e46e5f2fa251cf6846fca3.
Thanks!
