### ISSUE TITLE
Compare folders ignores files with _ (underscore)

### ISSUE THREAD

**Issue by SoundedSquash** [moshfeu/vscode-compare-folders#75]
I have a few files named ClassName_Test.cls or Object_ClassName.cls and those are getting ignored by Compare Folders in all 3 areas. I'm using this to compare Salesforce Apex classes and it works great for names that don't contain underscores.

**Comment by moshfeu** [comment]
Thanks for reporting this. I'll check if I can reproduce the issue and will keep you update.

**Comment by moshfeu** [comment]
Seems to work for me

<img width="422" alt="Screen Shot 2021-04-17 at 21 50 40" src="https://user-images.githubusercontent.com/3723951/115123766-31569c00-9fc7-11eb-8a00-6605b76c3046.png">

BTW, there are 4 areas. The 4th is "Identical Files". You can make it visible by turning on "compareFolders.showIdentical" option.
