### ISSUE TITLE
[error] EACCES: permission denied, scandir '//root'

### ISSUE THREAD

**Issue by qmutz** [moshfeu/vscode-compare-folders#76]
**Original message**: Oops, something went wrong while comparing**System Info**Editor version: 1.50.0Extension version: 0.20.1OS: linux 5.4.72-microsoft-standard-WSL2**Stack**Error: EACCES: permission denied, scandir '//root'

.log as I have TEST RUN an R4 2011 16 core @ 3.2 will not work on the folder FOR each ELSE if ELSE then is too much TASK on the COMPUTE and VALIDATION SERVICE or CVS. It is best to leave it device://root.*.* to URL with many monitoring services like GRAFANA they also said to not do the same as CACHED states are not GOALS or HISTORY. Group Hardware AKA GH is an Excellent EOF End of Field or FILE with response metrics that write dedicated services and only orient you by CLONES and UPDATES ALL LIVE., So by system services OR Internet SYSTEM SERVICES. IIS I think it is best as I leave just for MS containers and dialogs. THANKS multiple operating system hardware NO bugs so far.

**Comment by moshfeu** [comment]
Thanks for reporting this.
Please review #71 and let me know if you think it's the same problem
