### ISSUE TITLE
Comparing with remote workspace folder fails

### ISSUE THREAD

**Issue by mforkel** [moshfeu/vscode-compare-folders#81]
I tried to use Compare Folders in a workspace that contains local folders and remote folders accessed with the [SSH FS extension](https://github.com/SchoofsKelvin/vscode-sshfs). An attempt to compare a local folder to a remote folder results in an error message "Oops, something went wrong while comparing" and this output:
```
error while comparing
{
  "errno": -2,
  "code": "ENOENT",
  "syscall": "lstat",
  "path": "/scripts"
}
```
Comparing a local folder to the remote root folder gives this output:
```
error while comparing
{
  "errno": -13,
  "syscall": "lstat",
  "code": "EACCES",
  "path": "//mnt/c/DumpStack.log.tmp"
}
```
The file DumpStack.log.tmp is not accessible. In both cases, Compare Folders incorrectly report that there are no differences in any file at the same path.

Comparing a file in a local folder to a file in a remote folder works fine.

The [SSH FS documentation for remote workspace folders](https://github.com/SchoofsKelvin/vscode-sshfs#remote-workspace-folders) claims that SSH FS works with extensions using the [`vscode.workspace.fs` API](https://code.visualstudio.com/updates/v1_37#_vscodeworkspacefs). May be Compare Folders is no using that API?

**Comment by moshfeu** [comment]
Thanks for the report.
I'll look into it as soon as I can.

**Comment by qiyan98** [comment]
Same here. I was trying to compare two folders on the remote server and it took forever to load. The same folders on my local laptop work smoothly.

**Comment by moshfeu** [comment]
Hi @qiyan98 and @mforkel .
Sorry for the very late reply. I'm not using remote folders so I lack knowledge in that area. 
I'm not sure it's related but the extension uses an external library for comparison. I'm sure that the library doesn't use `vscode.workspace.fs` API because it's a normal node library.
Maybe I can ask the library`s owner to allow consumers to pass the `fs` module so in our case it would use `vscode.workspace.fs.

Do you know an easy way to connect to ssh so I could test it myself?

**Comment by mforkel** [comment]
Thanks for looking into this, moshfeu

> Do you know an easy way to connect to ssh so I could test it myself?

I'm not sure I understand your question. I guess a basic setup for testing would be a remote machine with an SSH server installed and your Windows machine with VS Code and the Remote SSH extension (see [Remote Development using SSH](https://code.visualstudio.com/docs/remote/ssh)). Than you could use your extension to compare folders on the remote and the local machine.
