### ISSUE TITLE
copy to compared performs no action

### ISSUE THREAD

**Issue by ihayhurst** [moshfeu/vscode-compare-folders#83]
Although I'm still finding my way around your extension, I have an issue: Selecting a  file  (only in My folder) and right click copy to compared isn't copying for me, I tried in V22.0  then updated to 22.1 incase it had been fixed,  however the same issue was present in V22.1
I am using vs code on a Windows machine remote ssh to a Linux host (CentOS 7.9) where both folders are being compared.
I haven't tried copying from the compared folder,  I have run a find just incase the file was copied to somwhereelse in the folder structure.

**Comment by moshfeu** [comment]
Thanks for the issues. Seems like these are issues with working on remote folders.
TBH, I don't have much experience with ssh but I'll do my best to fix this when I'll get to it.
