### ISSUE TITLE
feature: show line diff summary

### ISSUE THREAD

**Issue by unional** [moshfeu/vscode-compare-folders#89]
Hi,

Thank you for creating this extension. It is very useful.

I want to see if it is possible to show the summary of total line differences between the two folders.

Like how many lines are added, modified, or deleted.

**Comment by moshfeu** [comment]
Hi, I'm glad to hear!
This extensions relays on [dir-compare](https://github.com/gliviu/dir-compare) and unfortunately, seems like number of lines stat is not available.

@gliviu what do you think?

**Comment by gliviu** [comment]
Hello,
Line based statistics are not supported by [dir-compare](https://www.npmjs.com/package/dir-compare) out of the box.
To implement this scenario you will have to replace the default `compare by content` implementation. Take a look at [Custom file content comparators](https://github.com/gliviu/dir-compare#custom-file-content-comparators).

You will have to provide a new comparator that works similar to a diff tool and is able to understand when lines were removed or added.
The new comparator will update something like a global object that holds the created/modified/deleted line counts.

Maybe you could use a project like [diff](https://www.npmjs.com/package/diff) or similar to provide this logic.
