### ISSUE TITLE
Feature request: show missing/additional files

### ISSUE THREAD

**Issue by fbaligand** [moshfeu/vscode-compare-folders#9]
Currently, only differences from files with same paths are shown. 
It would be great to display also which files/folders are present in folder1 but not in folder2 (and the opposite).

**Comment by moshfeu** [comment]
Thanks!
This is a great feature. I'll do it as soon as I'll have some time.

**Comment by fbaligand** [comment]
Nice!

**Comment by moshfeu** [comment]
Just published v0.4.0.
Let me know what you think.
Thanks!

**Comment by fbaligand** [comment]
Great!
I will try it soon and give you feedback.

**Comment by fbaligand** [comment]
I just tried v0.4.0 version, and it works great!
Thanks for this enhancement!

**Comment by moshfeu** [comment]
Thank you 😊
Please consider to leave a review in the marketplace (hope it will be a good one 😉)

**Comment by fbaligand** [comment]
Done :)

**Comment by moshfeu** [comment]
Thank you!
If you have more ideas for features, well, you know what to do 😉

**Comment by fbaligand** [comment]
fine :)
