### ISSUE TITLE
Always Crashing

### ISSUE THREAD

**Issue by ravimyws** [moshfeu/vscode-compare-folders#90]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by moshfeu** [comment]
Hi @ravimyws, I'm not sure I understand the issue.

Can you describe the steps I should take in order to reproduce the issue? Can you also include [vscode info](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-find-the-version) and the extension version?

Thanks

**Comment by ravimyws** [comment]
Sure, I will do it today.

**Comment by ravimyws** [comment]
Some How the extension is working

**Comment by moshfeu** [comment]
Glad to hear :)
