### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by webtechiq** [moshfeu/vscode-compare-folders#92]
- Issue Type: `Bug`
- Extension Name: `compare-folders`
- Extension Version: `0.22.2`
- OS Version: `Darwin x64 21.3.0`
- VS Code version: `1.65.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by moshfeu** [comment]
Thank you!
What is the actual issue you are experiencing?
