### ISSUE TITLE
compare-folder cannot work with ssh fs extention

### ISSUE THREAD

**Issue by shiunyi71** [moshfeu/vscode-compare-folders#94]
Hi,

I always develop remotely via ssh fs extension.
I want to compare 2 dirs by compare-folder extension.
However, the compare-folder extension cannot find Folders.
I think this may cause by the compare-folder extension doses not supporting ssh dir.
many thanks.

**Comment by moshfeu** [comment]
Thank you for the report! Is it the same issue as #81 ?

**Comment by imkzh** [comment]
If you are on linux, you can mount the network file system (e.g. through sftp), 
if you mount the the network file system through GUI, will be possibly mounted at `/run/user/<uid>/gvfs/...` (dragging a file into terminal reveals it's real path),
you can then compare them as if on local.
