### ISSUE TITLE
[feature request] Add an option to auto exclude files from .gitignore

### ISSUE THREAD

**Issue by placasse** [moshfeu/vscode-compare-folders#96]
I compare two huge folders, which appear to be git repository.
There is a lot of temporary binary files and I'm using "compareFolders.excludeFilter" to remove them from comparison.
I feel like rewriting my gitignore in a different format.

**Comment by moshfeu** [comment]
It's a great idea, thank you.
Can you try the feature in the attached version?

[compare-folders-0.23.0.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/9275639/compare-folders-0.23.0.vsix.zip)

**Comment by moshfeu** [comment]
Keep
