### ISSUE TITLE
[feature request] Add 2 Buttons for First and Second Folder Select

### ISSUE THREAD

**Issue by necatiarslan** [moshfeu/vscode-compare-folders#99]
Can you add 2 buttons to select the first and second folders?
Now it isn't obvious to choose the first folder.
This should be a very straightforward feature for these types of tools.
thanks in advance

**Comment by moshfeu** [comment]
Thank you for the idea, I really appreciate it!

There is the `Compare Folders: Choose 2 folders and compare` command that can be run from the command palette.
What do you think about adding a button which triggers the command rather than having 2 buttons?
I'm asking because this extension "doesn't know" and prefer not to handle cases where there is only one folder selected so it can't show the diffs.

**Comment by necatiarslan** [comment]
I realized the command after your message.

I think, for a better UX
1. Not My Folder -->  Left Folder
2. Not Compared Folder --> Right Folder
3. Show the Left and Right Folder at the top of the extension
4. a Left and a Right Button would be great to easily select the folders
5. Add 'Add to Left Folder' and 'Add To Right Folder' to the context menu of explorer
6. Differences --> Different Content

I spend 15 minutes today to be able to find to compare 2 subfolders in my project.
I was not aware of the commands in the palette.

Really appreciate it if you add these functions.
1. File Filter (to focus only .py or .yaml files)
2. Exclude Files ( like *.html;gitignore) to completely ignore



Thanks

**Comment by imkzh** [comment]
@necatiarslan  

> 1.File Filter (to focus only .py or .yaml files)
> 2.Exclude Files ( like *.html;gitignore) to completely ignore

Filtering is already supported (in settings, or in workspace settings), you can search for `compareFolders.excludeFilter` and `compareFolders.includeFilter` to find them.

Currently, this extension first find all files matched by `compareFolders.includeFilter` and discard those matched by `compareFolders.excludeFilter`.

**Comment by necatiarslan** [comment]
> @necatiarslan
> 
> > 1.File Filter (to focus only .py or .yaml files)
> > 2.Exclude Files ( like *.html;gitignore) to completely ignore
> 
> Filtering is already supported (in settings, or in workspace settings), you can search for `compareFolders.excludeFilter` and `compareFolders.includeFilter` to find them.
> 
> Currently, this extension first find all files matched by `compareFolders.includeFilter` and discard those matched by `compareFolders.excludeFilter`.

can you add this to UI ?

**Comment by moshfeu** [comment]
@necatiarslan 
Since these properties are lists, vscode doesn't have a UI, only modifying the _settings.json_ file.

**Comment by moshfeu** [comment]
@necatiarslan I'm about to close this issue unless there is anything else I can do here

**Comment by necatiarslan** [comment]
its ok, thanks
